[tool.poetry]
name = "project_name"
version = "0.1.0"
description = "A basic Python project boilerplate."
authors = ["Your Name <youremail@example.com>"]
license = "MIT"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"